export {default as MainPage} from './main'
export {default as BlogPage} from './blog'
export {default as BlogAdmin} from './blogAdmin'
export {default as NotFoundPage} from './notfound'
export {default as AdminPage} from './admin'
export {default as TestPage} from './test'